//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CHI_TIET_HOA_DON
    {
        [Display(Name = "Mã sách")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string MA_SACH { get; set; }
        [Display(Name = "Mã hoá đơn")]
        [Required(ErrorMessage = "Không được để trống!")]
        public int MA_HD { get; set; }
        [Display(Name = "Số lượng sách")]
        [Required(ErrorMessage = "Không được để trống!")]
        [Range(0, int.MaxValue, ErrorMessage = "Hãy nhập số lượng hợp lệ!")]
        public Nullable<int> SL_SACH { get; set; }
        public Nullable<System.DateTime> DELETED_AT { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
