//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CHI_TIET_KHUYEN_MAI
    {
        [Display(Name = "Mã khuyến mãi")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string MA_KM { get; set; }
        [Display(Name = "Mã sách")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string MA_SACH { get; set; }
        public Nullable<System.DateTime> DELETED_AT { get; set; }
    
        public virtual KHUYEN_MAI KHUYEN_MAI { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
