//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CHI_TIET_NHAP_HANG
    {
        [Display(Name = "Mã sách")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string MA_SACH { get; set; }
        [Display(Name = "Mã đơn nhập")]
        [Required(ErrorMessage = "Không được để trống!")]
        public int MA_DON_NHAP { get; set; }
        [Display(Name = "Số lượng nhập")]
        [Required(ErrorMessage = "Không được để trống!")]
        [Range(0, int.MaxValue, ErrorMessage = "Hãy nhập số lượng hợp lệ!")]
        public Nullable<int> SL_NHAP { get; set; }
        [Display(Name = "Đơn giá nhập")]
        [Required(ErrorMessage = "Không được để trống!")]
        [DisplayFormat(DataFormatString = "{0:#,###.## vnđ}")]
        [Range(0, int.MaxValue, ErrorMessage = "Hãy nhập số tiền hợp lệ!")]
        public Nullable<double> GIA_NHAP { get; set; }
        public Nullable<System.DateTime> DELETED_AT { get; set; }
    
        public virtual DON_NHAP_HANG DON_NHAP_HANG { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
