//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_NHAP_HANG
    {
        public string MA_SACH { get; set; }
        public int MA_DON_NHAP { get; set; }
        public Nullable<int> SL_NHAP { get; set; }
        public Nullable<double> GIA_NHAP { get; set; }
        public Nullable<System.DateTime> DELETED_AT { get; set; }
    
        public virtual DON_NHAP_HANG DON_NHAP_HANG { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
