//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_HOA_DON
    {
        public string MA_SACH { get; set; }
        public int MA_HD { get; set; }
        public Nullable<int> SL_SACH { get; set; }
        public Nullable<System.DateTime> DELETED_AT { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
