//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CO_CV
    {
        [Display(Name = "Mã chức vụ")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string MA_CV { get; set; }
        [Display(Name = "Mã nhân viên")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string MA_NV { get; set; }
        [Display(Name = "Thời gian nhận chức")]
        [Required(ErrorMessage = "Không được để trống!")]
        public Nullable<System.DateTime> TG_NHAN_CHUC { get; set; }
        [Display(Name = "Thời gian từ chức")]
        [Required(ErrorMessage = "Không được để trống!")]
        public Nullable<System.DateTime> TG_TU_CHUC { get; set; }
        public Nullable<System.DateTime> DELETED_AT { get; set; }
    
        public virtual CHUC_VU CHUC_VU { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
