//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_CV
    {
        public string MA_CV { get; set; }
        public string MA_NV { get; set; }
        public Nullable<System.DateTime> TG_NHAN_CHUC { get; set; }
        public Nullable<System.DateTime> TG_TU_CHUC { get; set; }
    
        public virtual CHUC_VU CHUC_VU { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
