//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_GIA
    {
        public int MA_DG { get; set; }
        public Nullable<double> SO_TIEN { get; set; }
        public Nullable<System.DateTime> NGAY_AP_DUNG { get; set; }
        public string MA_SACH { get; set; }
        public Nullable<System.DateTime> DELETED_AT { get; set; }
    
        public virtual SACH SACH { get; set; }
    }
}
