//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KHUYEN_MAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHUYEN_MAI()
        {
            this.CHI_TIET_KHUYEN_MAI = new HashSet<CHI_TIET_KHUYEN_MAI>();
        }

        [Display(Name = "Mã khuyến mãi")]
        [Required(ErrorMessage = "Không được để trống!")]
        [MaxLength(20, ErrorMessage = "Mã khuyến mãi tối đa 20 kí tự!")]
        public string MA_KM { get; set; }
        [Display(Name = "Tên khuyến mãi")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string TEN_KM { get; set; }
        [Display(Name = "Ngày bắt đầu")]
        [Required(ErrorMessage = "Không được để trống!")]
        public Nullable<System.DateTime> BAT_DAU { get; set; }
        [Display(Name = "Ngày kết thúc")]
        [Required(ErrorMessage = "Không được để trống!")]
        public Nullable<System.DateTime> KET_THUC { get; set; }
        [Display(Name = "Tỉ lệ khuyến mãi")]
        [Required(ErrorMessage = "Không được để trống!")]
        public Nullable<double> TI_LE_GIAM { get; set; }
        [Display(Name = "Mô tả khuyến mãi")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string MO_TA_KM { get; set; }
        [Display(Name = "Điều kiện")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string DIEU_KIEN { get; set; }
        public Nullable<System.DateTime> DELETED_AT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_KHUYEN_MAI> CHI_TIET_KHUYEN_MAI { get; set; }
    }
}
