//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NHA_CUNG_CAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHA_CUNG_CAP()
        {
            this.DON_NHAP_HANG = new HashSet<DON_NHAP_HANG>();
        }

        [Display(Name = "Mã nhà cung cấp")]
        [Required(ErrorMessage = "Không được để trống!")]
        [MaxLength(20, ErrorMessage = "Mã nhà cung cấp tối đa 20 kí tự!")]
        public string MA_NCC { get; set; }
        [Display(Name = "Tên nhà cung cấp")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string TEN_NCC { get; set; }
        [Display(Name = "Địa chỉ nhà cung cấp")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string DIACHI { get; set; }
        [Display(Name = "Thông tin liên lạc")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string LIENLAC { get; set; }
        [Display(Name = "Tổng số sách đã nhập")]
        public Nullable<int> TONG_NHAP { get; set; }
        public Nullable<System.DateTime> DELETED_AT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DON_NHAP_HANG> DON_NHAP_HANG { get; set; }
    }
}
