//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.DON_NHAP_HANG = new HashSet<DON_NHAP_HANG>();
            this.HOA_DON = new HashSet<HOA_DON>();
            this.KHUYEN_MAI = new HashSet<KHUYEN_MAI>();
        }
    
        public string MA_SACH { get; set; }
        public string MA_DS { get; set; }
        public string MA_TL { get; set; }
        public string TEN_SACH { get; set; }
        public string ANH_BIA { get; set; }
        public string MO_TA_SACH { get; set; }
        public Nullable<int> GIA_BAN { get; set; }
        public string TAC_GIA { get; set; }
        public string NHA_XB { get; set; }
        public Nullable<System.DateTime> NAM_XB { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual DANG_SACH DANG_SACH { get; set; }
        public virtual THE_LOAI THE_LOAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DON_NHAP_HANG> DON_NHAP_HANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUYEN_MAI> KHUYEN_MAI { get; set; }
    }
}
