//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.DON_NHAP_HANG = new HashSet<DON_NHAP_HANG>();
            this.HOA_DON = new HashSet<HOA_DON>();
            this.KHUYEN_MAI = new HashSet<KHUYEN_MAI>();
        }
        [Display(Name = "Mã sách")]
        [Required(ErrorMessage = "Không được để trống!")]
        [MaxLength(20, ErrorMessage = "Mã sách tối đa 20 kí tự!")]
        public string MA_SACH { get; set; }
        [Display(Name = "Mã dạng sách")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string MA_DS { get; set; }
        [Display(Name = "Mã thể loại")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string MA_TL { get; set; }
        [Display(Name = "Tên sách")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string TEN_SACH { get; set; }
        [Display(Name = "Ảnh bìa")]
        public string ANH_BIA { get; set; }
        [Display(Name = "Mô tả sách")]
        public string MO_TA_SACH { get; set; }
        [Display(Name = "Giá bán")]
        [Required(ErrorMessage = "Phải nhập vào một số!")]
        [DisplayFormat(DataFormatString = "{0:#.###,## ₫}")]
        [Range(0, int.MaxValue, ErrorMessage = "Hãy nhập số tiền hợp lệ!")]
        public Nullable<int> GIA_BAN { get; set; }
        [Display(Name = "Tác giả")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string TAC_GIA { get; set; }
        [Display(Name = "Nhà xuất bản")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string NHA_XB { get; set; }
        [Display(Name = "Năm xuất bản")]
        public Nullable<System.DateTime> NAM_XB { get; set; }
        [Display(Name = "Số lượng tồn kho")]
        [Range(0, int.MaxValue, ErrorMessage = "Hãy nhập số lượng hợp lệ!")]
        public Nullable<int> SOLUONG { get; set; }
        public virtual DANG_SACH DANG_SACH { get; set; }
        public virtual THE_LOAI THE_LOAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DON_NHAP_HANG> DON_NHAP_HANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUYEN_MAI> KHUYEN_MAI { get; set; }
    }
}
