//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TAI_KHOAN
    {
        [Display(Name = "Tài khoản")]
        [Required(ErrorMessage = "Không được để trống!")]
        [MaxLength(20, ErrorMessage = "Tên tài khoản tối đa 20 kí tự!")]
        public string USERNAME { get; set; }
        [Display(Name = "Mã nhân viên")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string MA_NV { get; set; }
        [MaxLength(100, ErrorMessage = "Mật khẩu tối đa 100 kí tự!")]
        [Display(Name = "Mật khẩu")]
        [Required(ErrorMessage = "Không được để trống!")]
        [DataType(DataType.Password)]
        public string PASSWORD { get; set; }
        [Display(Name = "Quyền")]
        [Required(ErrorMessage = "Không được để trống!")]
        public string QUYEN { get; set; }
        public Nullable<System.DateTime> DELETED_AT { get; set; }
    
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
